# Make sure ocamlbuild can find opam-managed packages: first run
#
# eval `opam config env`

# Easiest way to build: using ocamlbuild, which in turn uses ocamlfind

.PHONY : all
all : automatic.native

.PHONY : test
test : automatic.test

.PHONY : automatic.native
automatic.native :
	rm -f *.o
	ocamlbuild -use-ocamlfind -pkgs llvm,llvm.analysis -cflags -g,-w,+a-4 \
        automatic.native

.PHONY : automatic.test
automatic.test :
	rm -f *.o
	ocamlbuild -use-ocamlfind -pkgs llvm,llvm.analysis,bisect_ppx -cflags -g,-w,+a-4 \
        automatic.native

# "make clean" removes all generated files

.PHONY : clean
clean :
	ocamlbuild -clean
	rm -rf testall.log *.diff automatic scanner.ml parser.ml parser.mli
	rm -rf *.cmx *.cmi *.cmo *.cmx *.o *.s *.ll *.out *.exe

# More detailed: build using ocamlc/ocamlopt + ocamlfind to locate LLVM

OBJS = ast.cmx p_ast.cmx sast.cmx codegen.cmx parser.cmx p_parser.cmx scanner.cmx p_scanner.cmx semant.cmx preprocess.cmx automatic.cmx

automatic : $(OBJS)
	ocamlfind ocamlopt -linkpkg -package biseect_ppx -package llvm -package llvm.analysis $(OBJS) -o automatic

scanner.ml : scanner.mll
	ocamllex scanner.mll

p_scanner.ml: p_scanner.mll
	ocamllex p_scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

p_parser.ml p_parser.mli : p_parser.mly
	ocamlyacc p_parser.mly

%.cmo : %.ml
	ocamlc -g -c $<

%.cmi : %.mli
	ocamlc -g -c $<

%.cmx : %.ml
	ocamlfind ocamlopt -c -package llvm $<

### Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo :
ast.cmx :
p_ast.cmo :
p_ast.cmx :
codegen.cmo : ast.cmo
codegen.cmx : ast.cmx
automatic.cmo : preprocess.cmo semant.cmo scanner.cmo parser.cmi codegen.cmo ast.cmo
automatic.cmx : preprocess.cmx semant.cmx scanner.cmx parser.cmx codegen.cmx ast.cmx
preprocess.cmo : p_scanner.cmo p_parser.cmi p_ast.cmo
preprocess.cmx : p_scanner.cmx p_parser.cmx p_ast.cmo
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi
p_parser.cmo : p_ast.cmo p_parser.cmi
p_parser.cmx : p_ast.cmx p_parser.cmi
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
p_scanner.cmo : p_parser.cmi
p_scanner.cmx : p_parser.cmx
semant.cmo : ast.cmo
semant.cmx : ast.cmx
parser.cmi : ast.cmo
p_parser.cmi: p_ast.cmo
