version: 2
jobs:
  build:
    docker:
      - image: nsgomez/coms4115-docker:stable

    working_directory: ~/autoMATic
    environment:
      - TERM: dumb

    shell: /bin/bash
    steps:
      - checkout
      - run:
          name: Configure OCaml environment
          command: echo '. /home/opam/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true' >> $BASH_ENV

      - run:
          name: Build language
          command: make test

      - run:
          name: Run test suite
          command: ~/autoMATic/test.sh

      - run:
          name: Generate coverage report
          command: ocveralls --repo_token $COVERALLS_REPO_TOKEN --git --prefix _build bisect*.out --send
          when: always
